### ISSUE TITLE
DFDL Language remove "xs:" prefix

### ISSUE THREAD

**Issue by Shanedell** [apache/daffodil-vscode#120]
- This only needs to be done once Daffodil decided to fully move away from the prefix.
- Issue made based on comment --> https://github.com/apache/daffodil-vscode/pull/117#discussion_r883666880

**Comment by Shanedell** [comment]
> One thing to consider is this "xs" prefix isn't mandatory and some schemas use different prefixes (usually "xsd" or no prefix). Ideally this would look at the in scope namespaces an find the prefix associated with the schema prefix.
> 
> Again, I won't block the merge for that, but hope those kinds of features are added in the future.


Also note this comment from @stevedlawrence

**Comment by scholarsmate** [comment]
It appears there are still several instances in the TypeScript code where the `xs:` prefix remains.
