### ISSUE TITLE
Intellisense Documentation

### ISSUE THREAD

**Issue by Shanedell** [apache/daffodil-vscode#167]
- Create documentation for the Intellisense of the DFDL language extension
- Where should this documentation live?
  - Wiki
  - Intellisense.md (inside of repo)
  - Confluence

**Comment by scholarsmate** [comment]
My preference would be that the documentation lives within the repo (e.g., intellisense.md).

**Comment by kirkejohnson** [comment]
What is the intent/goal of the documentation?  What is the acceptance criteria for this Issue?

**Comment by scholarsmate** [comment]
To get the ball rolling on this issue, we have started a wiki page https://github.com/apache/daffodil-vscode/wiki/Using-DFDL-Intelli-sense with the contents of the Intellisense readme.  We can collaborate on the documentation there,

**Comment by scholarsmate** [comment]
Intellisense documentation is posted to the daffodil-vscode repository wiki.
