### ISSUE TITLE
REQ-TDML-05  The extension shall provide an item in the command palette (ctrl + shift + p) for ‘Add Test Case to TDML File’

### ISSUE THREAD

**Issue by scholarsmate** [apache/daffodil-vscode#172]
**The extension shall provide an item in the command palette (ctrl + shift + p) for ‘Add Test Case to TDML File’.**

Selecting this command shall bring up menus allowing the user to select the following:

- TDML File Name
- Name for the test case
- Description for the test case
- DFDL Schema
- Data Document

This selection shall work in the same way as the DFDL debugger where if you select the command from a DFDL Schema, it will automatically use that in place of a selection.

**Comment by michael-hoke** [comment]
Unit Testing:

- Make a TDML file with Generate, and call Append using that file. Verify that the new file contains two test cases and that the added test case and the pre-existing test case are those test cases.
- Test that the LaunchArgs validation works in the scala side (Parse.scala)
- Mock the TDML code, and test a pass case for an append
- Test that the validation works on the Typescript side

**Comment by arosien** [comment]
Closed by #253.

**Comment by arosien** [comment]
Closed by #253.
