### ISSUE TITLE
REQ-TDML-06 Extension shall provide an item in the command palette (ctrl + shift + p) for ‘Run Test Case in TDML File’

### ISSUE THREAD

**Issue by scholarsmate** [apache/daffodil-vscode#173]
**The extension shall provide an item in the command palette (ctrl + shift + p) for ‘Run Test Case in TDML File’.**

Selecting this command shall bring up menus allowing the user to select the following:

- TDML File Name
- Test Case to run (This list shall be populated with data in the selected TDML File)
- 

This command shall start the Daffodil process in run mode. This command should provide an option to start the Daffodil process in debug mode. The location of the DFDL Schema shall be expected to be relative to the location of the TDML File. It shall be the user who created the TDML file’s responsibility to ensure that packaging of their TDML file is correct.

**Comment by michael-hoke** [comment]
Unit Testing:

- Create a TDML file with Generate. Run it through Execute and verify the output.
- Test that the LaunchArgs validation works in the scala side (Parse.scala)
- Mock the TDML code, and test a pass case for a Execute
- Test that the validation works on the Typescript side

**Comment by arosien** [comment]
Closed by #253.
