### ISSUE TITLE
Enable Scala Steward dependency checking/updates

### ISSUE THREAD

**Issue by stevedlawrence** [apache/daffodil-vscode#185]
Dependabot does not know about Scala/SBT dependencies or how to update them. For that, [Scala Steward](https://github.com/scala-steward-org/scala-steward) can be used. We should open a pull request to the Scala Steward project to add apache/daffodil-vscode to repos-github.md so to enabble dependency updates for the scala code in this repo.

**Comment by Shanedell** [comment]
@stevedlawrence I was on the same track as you I made a duplicate item for this. But I closed so that this one will be the main tracker. Is this the way you did Daffodil? I was wondering if we wanted to use the Scala Steward GitHub Action ( (https://github.com/scala-steward-org/scala-steward-action)?

**Comment by stevedlawrence** [comment]
For Daffodil we just needed to add our repo here: https://github.com/scala-steward-org/repos/

However, according to that it looks like as of June 1st that's been disabled. So we'll need to find another alternative.

I think the scala-steward-action you found is probably the best approach. Maybe try adding that to the vscode repo and if it seems to work we can copy the changed over to the Daffodil repo too?

**Comment by Shanedell** [comment]
That sounds good to me I will look into it

**Comment by Shanedell** [comment]
@stevedlawrence Do you want the Scala Steward CI stuff to be included in `CI.yml` or make it separate?

**Comment by stevedlawrence** [comment]
I think it might need to be in a separate workflow since our CI workflow is trigger on pushes and pull requests, but the scala stewards wants to be triggered by a cron job schedule. I don't think github actions lets you have different triggers in the same workflow file.

**Comment by Shanedell** [comment]
@stevedlawrence How often do you think the cronjob should run, once a week, once a day?
