### ISSUE TITLE
Add build instructions to the readme

### ISSUE THREAD

**Issue by jw3** [apache/daffodil-vscode#23]
No where in the README are there build dependencies or instructions. Apache is very source code focused, so instructions should first and foremost be about how to build things from source. It's fine to also provide convenience binaries, whether they be from downloads.apache.org or via the marketplace, but that's importtation information that should be in this README. It doesn't need to be part of this PR, but a new issue should be opened to add that information.

_Originally posted by @stevedlawrence in https://github.com/apache/daffodil-vscode/pull/22#discussion_r727022373_

**Comment by jw3** [comment]
https://github.com/apache/daffodil-vscode/wiki/Developers

**Comment by stevedlawrence** [comment]
Looks like you've got the wrong yarn: https://github.com/yarnpkg/yarn/issues/2821

That thread lists a handful of work arounds.
