### ISSUE TITLE
1.1.0-RC1 Issue - launch wizard

### ISSUE THREAD

**Issue by Shanedell** [apache/daffodil-vscode#246]
Issues inside of the rc1 release of 1.1.0:

- launch wizard is broken and non functional inside of the VSIX for rc1 release of 1.1.0

**Comment by stevedlawrence** [comment]
I would recommend creating two separate issues for these and adding them to the 1.1.0 milestone. That way they can be tracked, fixed, and reviewed in separate PRs.
