### ISSUE TITLE
When debug session ends, the binary display of hex data goes away

### ISSUE THREAD

**Issue by scholarsmate** [apache/daffodil-vscode#266]
When debug session ends, the binary display of hex data goes away. Why? I might be very interested in looking at that still. It can be marked inactive like the infoset file is, but shouldn't just be closed. You may not want to fix this soon because I expect the hex display will be replaced by the data editor in a view mode at some point, but anyway, it shouldn't auto-close just because the parse ended.

**Comment by Shanedell** [comment]
This is a pretty easy fix will add this 1.2.0 as it should not take long.

**Comment by Shanedell** [comment]
The hex display will eventually be removed in favor of the omega-edit editor but this transition is not planned until at least 1.5.0 I believe.

**Comment by Shanedell** [comment]
@mbeckerle I believe you noticed this on the latest release. Are you saying the file `datafile-hex` file is removed completely? If so this should not be what happens, it is closed out so its not open in the editor but the file should still be available to look at and reopen. Would this be the desired behavior or was this issue to make it so the file wasn't closed out in the editor after debug either?

**Comment by Shanedell** [comment]
Okay so the hexview should stay opened, with some styling differences on debug end. That makes sense to me
