### ISSUE TITLE
Akka dependency switching to incompatible BSL 1.0 license

### ISSUE THREAD

**Issue by stevedlawrence** [apache/daffodil-vscode#284]
Akka has announced that they are switching to the Business Source License 1.0. A discussion about whether this is compatible with ALv2 has been started in [LEGAL-619](https://issues.apache.org/jira/browse/LEGAL-619), but it pretty clearly seems incompatible.

Akka is a dependency of omega-edit and thus a dependency of VS Code. As long as omega edit uses an old version of Akka we are fine, but it means we can only upgrade to 3 year old versions of Akka when the license switches to ALv2. This is not ideal, so we should plan to work with omega edit to have this dependency removed to ensure no issues and to allow us to keep up with the latest versions of dependencies.

**Comment by scholarsmate** [comment]
Good find @stevedlawrence, this issue should be opened up over on the omega-edit repo.

**Comment by arosien** [comment]
Omega-edit issue: https://github.com/ctc-oss/omega-edit/issues/425
