### ISSUE TITLE
Investigate two TS tests that cause weird output

### ISSUE THREAD

**Issue by shanedell** [apache/daffodil-vscode#300]
In the process of making new tests for the suite extension they were two tests:

- `Available by default`
- `Available when inDebugMode`

When testing they would show as failed tests under that omega-edit suite.

However, now they seem to produce output like they are failing inside of the omega-edit test suite but don't show up as failed tests.

**Comment by scholarsmate** [comment]
@Shanedell is this something that we need to address before v1.2.0 is completed?

**Comment by Shanedell** [comment]
I don't think so, I honestly think this may have also been resolved will need to check in on it further

**Comment by Shanedell** [comment]
When further looking into this I don't think I see this happening anymore. There is some weird output in the CI but I don't think that is caused by us just something weird with the runner printing log statement perhaps?
