### ISSUE TITLE
REQ: Handle different logical byte sizes and bit ordering

### ISSUE THREAD

**Issue by scholarsmate** [apache/daffodil-vscode#311]
There exist data formats that have byte sizes other than 8 bits.  Additionally, the least significant bit may occupy an offset/address that is lower then the most significant bit.

mil-std-2045 is an example where characters are encoded in a packed 7-bit ASCII format, and the logical bytes are ordered with the least significant byte first (LSB is at a lower offset/address).

I have adjusted the wireframe in response to this use case in an attempt to facilitate such use case.

<img width="1474" alt="Wireframe-v2-1" src="https://user-images.githubusercontent.com/2205472/193117890-c626b479-c3d2-4eed-8524-e7a018a06b3e.png">

**Comment by scholarsmate** [comment]
The workflow for 7-bit ASCII and LSB at a lower offset, the user would select Bit for Offset, which would force the encoding to be binary, 7 would be selected as the logical byte size, and Lower Offset would be selected for the LSB.  Then the user would click and drag to select the bit offset range (the UI will force the range to be in multiples of the logical byte size).  In the second viewport, the user will see the range selected as 7-bit bytes (behind the scenes, the logical byte is left padded to fill an 8-bit byte so that we can display the byte values).  Overwrites are pretty straight-forward except the values given must fit inside the logical bytes (for 7-bit bytes, that's 0 - 127 decimal).  Inserts are complex since memory and files use 8-bit bytes and inserting 7 bits in the middle of the file means shifting all the bits right and creating a new byte at the end of the file to handle the overflow.  This can be a massive amount of change, especially when editing large files where the inserts are not done near the end of the file.  Delete is similarly complex.

I think for the initial implementation, that we only allow inserts and deletes when the byte size is 8-bits and we're byte aligned.

**Comment by mbeckerle** [comment]
Sorry to be so delayed in review of this. 

Suggest the GUI should use standard DFDL terminology, not try to introduce new concepts like lower-offset/higher-offset. or logical byte where the size might not be 8 bits.

For bits, those terms just beg the question. Higher offset from where? Where does it start.

The DFDL bit order terms are "least significant bit first" (abbreviated LSBF) or "most significant bit first" (MSBF). 

The constant is the place-value of the bit in its contribution to the numeric value of the whole byte. 

The "bit that represents the 2^7 place value" is an entirely unambiguous way to refer to a bit.  Within an 8 bit byte (unsigned conceptually, values 0 to 255 max), the 2^7 bit is the most-significant bit. The 2^0 bit is the least significant. 

Which of those is at bit position 1? Depends on MSBF or LSBF. 

The significance of the bits isn't changing, the bit position numbering scheme is changing. Consider 0x31 aka 49 or binary 00110001

Consider it as a number, not some representation in a computer. 

As a binary number, the most significant 4 bits are 0011 the least significant 4 bits are 0001. None of that changes regardless of what bit order you choose. The value is always 0x31 or 49 hex for this byte. 

Bit order just says how do you number the positions

87654321 (LSBF) or
12345678 (MSBF)

And that *only* matters if you are talking about parts of a byte. Is bit 5 a 0 or a 1.

in 0011**0**001 MSBF bit 5 is a 0. 
in 001**1**0001 LSBF bit 5 is a 1. 

There is one knob/setting that is purely about how the data is displayed on the viewport and that is about bytes being displayed left to right or right to left. 

So the viewport should allow you to choose whether to present the bytes from left to right (used with MSBF and big-endian typically, or to present the bytes right to left (used with LSBF and littleEndian typically). 
 
You also introduced a notion of logical byte having differing bit widths - this is not a DFDL concept. 
Suggest you avoid introducing this. 

In DFDL, logical means "about the infoset" not the representation. 

In the representation, the term "byte" always means an 8 bit 'octet' in the DFDL spec.  

In DFDL representation 'text' a character encoding's _code units_ can be smaller than a whole byte. But a representation byte is always 8 bits regardless of how the character code units are laid out on them. 

If you are talking about carving up the data stream into a bunch of consecutive 7-bit pieces, in DFDL you can only do that when you are talking about text. Specifically text having a character encoding with 7-bit 'width' for each character code unit. 

In DFDL if you define a format which is a 7-bit integer of type "xs:byte" we say your logical type is xs:byte (number  with range from -128 to +127) is populated from 7 specific bits in the representation. Those 7 bits may come from within 1 byte of representation, or they may come from 7 bits that span 2 bytes in the representation. 

<element name="x" type="xs:byte" dfdl:lengthUnits='bits' dfdl:length="7" dfdl:representation="binary" 
   dfdl:binaryNumberRep="binary"/>

This is an element which is of type xs:byte, where the value of that byte is taken from a 7-bit wide signed integer (2's complement) representation.

**Comment by mbeckerle** [comment]
Useful Idea perhaps:

This table is from the mil-std-2045 specification (which is public):

![image](https://user-images.githubusercontent.com/1524099/216728969-bd2d5761-d68f-4952-b9e5-339212ecf031.png)

The columns "value" and "field fragments" are pretty interesting. 

This table would have looked better if they had used a fixed-width font, but the point is that to show the bits, there are no natural boundaries, so you need to be able to point at any bit boundary and say "linebreak" and have it push the stuff to the left down to the next line. 

Also the way the reconcile bits to bytes is interesting. They allow you to "paint" a byte with X chars so that you can have a line about a bit field, and use "XX1XXXXX" to show its placement in a byte. Notice how in the table it takes 6 rows to cover the fields that make up only the first octet of data. 

An interactive mode that used this sort of display would have something like their field fragments column, with the X's filled in automatically so if you break the middle of a byte down to the next line, the right number of XXX chars show up to show the bits that are unavailable due to being taken up by fields described above. 

I'm attaching this spec doc to this ticket for your perusal.

**Comment by mbeckerle** [comment]
[MIL-STD-2045_47001D_CHANGE-1.pdf](https://github.com/apache/daffodil-vscode/files/10583529/MIL-STD-2045_47001D_CHANGE-1.pdf)

**Comment by scholarsmate** [comment]
Thanks for this useful input @mbeckerle, the team has been working on the Data Editor and we hope to have it ready for review very soon and we're going to need your input as we kick the tires.  It won't satisfy all these needs initially, but hopefully we can iterate and converge on a reasonable solution.

**Comment by nlewis05** [comment]
Unsure why this issue was reopened and put in 1.4.0
