### ISSUE TITLE
Support Daffodil different infoset options in the debugger

### ISSUE THREAD

**Issue by Shanedell** [apache/daffodil-vscode#343]
The Daffodil Scala debugger needs to be updated to support different input/output options for the infoset that are defined inside of Daffodil. These include SAX, JSON, etc.

@stevedlawrence @mbeckerle would you guys mind leaving a comment about all the different types of input and/or output supported by Daffodil for the infoset that you would like to be supported by the debugger?

**Comment by stevedlawrence** [comment]
I'm not too familar with VS Code, but it looks like this is the function of interest:

**Comment by stevedlawrence** [comment]
I'm not too familiar with VS Code extension, but it looks like this is the function of interest:

https://github.com/apache/daffodil-vscode/blob/main/server/core/src/main/scala/org.apache.daffodil.debugger.dap/Parse.scala#L777-L789

In that function, you use the `XMLTextInfosetOutputter` to write the infoset to a String as XML.

Here are the different infoset inputters and outputters Daffodil has built-in:

https://daffodil.apache.org/docs/latest/javadoc/org/apache/daffodil/japi/infoset/package-frame.html

Note that SAX uses a different API, so you would need to use the `DataProcessor.newXMLReaderInstance()` to get a SAX `XMLReader`, and then you can use normal SAX APIs/ContentHandlers/etc.

That said, most of those don't output to text so if you use them they would require extra processing, and probably wouldn't have much benefit to mos users, unless you need to do some preprocessing before user display. I would say only the `XMLTextInfosetOutputer` and maybe `JsonInfosetOutputter` would be of use to most users.
