### ISSUE TITLE
Omega Edit Hangs

### ISSUE THREAD

**Issue by mbeckerle** [apache/daffodil-vscode#364]
When evaluating 1.2.0-RC3, I tried using Omega-Edit. After enabling experimental feature, I chose Omega-Edit and my VSCode instance froze and had to be killed. This is repeatable for me. I don't even get to where I can point it at a data file.

**Comment by Shanedell** [comment]
@scholarsmate Should this be closed with the Data Editor updates we merged in the other day?

**Comment by scholarsmate** [comment]
This is OBE.
