### ISSUE TITLE
Broken link on release page for 1.2.0

### ISSUE THREAD

**Issue by mbeckerle** [apache/daffodil-vscode#365]
The link for Intellisense Instructions, click on it and it takes you to a "create a new page" situation on the Wiki.

**Comment by lrbarber** [comment]
The link to download the binaries is also broken: `The requested file does not exist in our mirror system or in our archives.`

**Comment by stevedlawrence** [comment]
I just pushed a change to fix the VS Code binaries. This bug was auto-closed, reopening since the intellisense issue is not fixed. I'm not sure what the correct link for that is.

**Comment by stevedlawrence** [comment]
Reopening. It's odd that commits in the daffodil-site repo auto-close issues in the daffodil-vscode repo...

**Comment by tuxji** [comment]
@stevedlawrence I have a checkout of a fork of the vscode repo. Yesterday I ran git pull, git rebase asf/main, git push.  I was only keeping my fork up to date.  However, I got an unexpected email from GitHub Actions telling me a CI run failed. I found out my fork's settings had had Actions enabled and had been running the workflows for a while (no longer, I've disabled my fork's Actions now). Either running a workflow or simply pushing the commit must have auto closed this issue.

**Comment by tuxji** [comment]
BTW, I also have a checkout of a fork of the daffodil-site repo and the same situation also happened there.  I had also run git pull, git rebase asf/main, git push in my checkout yesterday and my fork also had had Actions enabled too (no longer, they're disabled now).

**Comment by Shanedell** [comment]
Reopening, closed in a commit by mistake, was supposed to close #366 .

**Comment by stevedlawrence** [comment]
My commit did not fix the original issue, it only fixed the comment about binary links broken here https://github.com/apache/daffodil-vscode/issues/365#issuecomment-1371008143

The link Mike is talking about is on this page: https://daffodil.apache.org/vscode/1.2.0/, which is still broken.
