### ISSUE TITLE
Dependabot and scala-steward limit running

### ISSUE THREAD

**Issue by Shanedell** [apache/daffodil-vscode#372]
The MRs created by dependabot and scala-steward are becoming a bit much to keep up with. I think we should change how often these execute and open PRs.

Currently this how often they run:

```txt
- dependabot:
  * npm --> weekly
  * github-actions --> weekly

- scala-steward --> weekly
```

I propose updating all 3 to only run monthly or every other week.

**Comment by Shanedell** [comment]
@mbeckerle @stevedlawrence @tuxji @scholarsmate Any input on what would be best for limited amount of runs?

**Comment by scholarsmate** [comment]
Every 2 weeks or monthly is fine with me.  We'll want to know about security fixes in our software supply chain as soon as practical though.
