### ISSUE TITLE
Update test suite to support daffodil-debugger

### ISSUE THREAD

**Issue by Shanedell** [apache/daffodil-vscode#377]
Currently the test suite does not actually run the `daffodil-debugger`. We want to update the test suite to run the `daffodil-debugger` and then run tests against it, similar to how we do the `omega-edit` tests. Based on prelim looks this issue will most likely work in tandem with #301 as a lot of the code for running the `daffodil-debugger` will need to shared between the actual extension code and the suite.

**Comment by stevedlawrence** [comment]
I don't believe that license of the png schema is compatible with ALv2.

I would suggesion just make the `test.dfdl.xsd` a valid DFDL schema. I think it just needs a `dfdl:format` annotation, and maybe a couple dfdl properties defined to get it working.

**Comment by mbeckerle** [comment]
Presumably to test the VSCode IDE in general we'll need a bunch of schemas allowing its functionality to be exercised in tests. Some of these schemas will need to be correct for debugger testing. Others will want to have errors in them to test authoring support such as tying diagnostics from Daffodil to the graphical presentation of those lines of the schema.

**Comment by Shanedell** [comment]
@mbeckerle That is the future plan and why this needs added asap. My idea was having CI or tests clone the schemas, build them, set the necessary items and then run them through the debugger. For example doing the process you had posted for testing with pcap and ethernet, I would like to get that automated.
