### ISSUE TITLE
eliminate launch.json configuration steps

### ISSUE THREAD

**Issue by mbeckerle** [apache/daffodil-vscode#38]
We need a "new..." wizard that creates these launch configurations from a dialog. 

The dialog should have a place for users to enter everything they have to customize in the launch.json today.

**Comment by Shanedell** [comment]
I have an idea for this. Basically what I was thinking was creating a command that will act as a `launch.json` config wizard.

So would create a new command, something like `launch.config`, and add an icon for it up in the toolbar like the hex and infoset commands. Not sure what icon to use maybe just a gear icon?

Whenever the command is ran via command palette or by clicking on the toolbar icon, the user will be prompted with different input items:
- A file picker to select the file to be used for program and data
- A quick picker with either `true` or `false` for the boolean launch variables, eg `useExistingServer`, `stopOnEntry`. - A input box for other more specific values like `debugServer`

Once all the inputs are retrieved the command will output the json to `.vscode/launch.json`. Everytime this command is ran the `launch.json` would be overwritten with the newly given information.

Would this be a good approach? I have a little bit of code going for it now but for to put this up earlier

**Comment by stevedlawrence** [comment]
Is manual configuration of lanuch.json files just the expected way to use VS Code? I created a very simple HelloWorld.java file, opened the directory in VS Code, and clicked "Start Debugging". When I did that, VS Code prompted me with "To customize Run and Debug, create a launch.json file". I clicked that it it created a launch.json file with some fields auto-filled in.

So maybe this is just how people are used to using VSCode, and we don't necessarily need a special wizard? Maybe we just need to make sure the extension recognizes directories containing with *.dfdl.xsd files as DFDL projects, and know how to provide a reasonable launch.json for such projects?

I guess what I'm saying is we might no want to invent the wheel, but see how VS Code handles debugging things like Java/C/etc. and just do something similar? Assuming that is reasonably user friendly.

**Comment by mbeckerle** [comment]
My $0.02. Not sure "how VSCode does it for other things" is good precedent for our community. Some/Most are not so much professional programmers who will have prior experience with VSCode.  So they will have no prior experience of it (e.g., I had not prior experience with VSCode, so for me, creating a launch.json file feels like "why isn't there a dialog that constructs this thing for me?"

**Comment by mbeckerle** [comment]
A launch.json config wizard sounds like the right thing to me. At least one that creates the basic launch.json. It needn't support every advanced launch property for version 0.1 of this dialog.

**Comment by jw3** [comment]
> Would this be a good approach?

@Shanedell yes what you described sounds good.  A dialog launchable from the toolbar/palette that provides configuration of 
1. input file
2. schema file
3. stop on entry (default to true)
4. infoset output path (nullable)

I'd say that the other options are advanced and do not need exposed in this first iteration.

**Comment by jw3** [comment]
Since you already have it implemented go ahead and PR it and let's see what it looks like.
