### ISSUE TITLE
Create portable documentation

### ISSUE THREAD

**Issue by scholarsmate** [apache/daffodil-vscode#380]
The documentation for the Apache Daffodil™ Extension for Visual Studio Code is maintained on the project wiki.  There are times where having a portable document (like a .docx or .pdf) is desired.

**Comment by Shanedell** [comment]
This is closed via PR's:

- https://github.com/apache/daffodil/pull/897
- https://github.com/apache/daffodil-site/pull/103

Once both are closed I will close this ticket

**Comment by Shanedell** [comment]
Both PRs were merged so I am closing this issue.
