### ISSUE TITLE
Document required glibc for Linux

### ISSUE THREAD

**Issue by scholarsmate** [apache/daffodil-vscode#382]
The Ωedit Linux build is being done on Ubuntu 20.04 LTS.  Linux OSes using different a version of glibc than then system we built it on will not be compatible.

**Comment by mbeckerle** [comment]
Isn't glibc a C-callable library? Isn't there a binary compatible linkage convention for C that glibc obeys? So incompatibility is only if the signatures of functions/procedures change across versions of glibc. That would be my expectation anyway.

So I guess I need more explanation of why this incompatibility occurs.

**Comment by scholarsmate** [comment]
To put it simply, glibc is backward compatible, but not forward compatible.  If we link against a more recent version of glibc, the linker is going to link against the most recent version of a symbol.  Take that binary to a system with an older glibc and your symbols might not resolve because the newer symbols don't exist.  Take a binary build on a system with an older glibc to a system with a newer glibc and it ought to work because glibc carries around the older symbol versions, providing some guarantee of backwards compatibility.  I hope that helps.

**Comment by scholarsmate** [comment]
Added a bullet to https://github.com/apache/daffodil-vscode/wiki/Apache-Daffodil%E2%84%A2-Extension-for-Visual-Studio-Code#prerequisites to cover this dependency.
