### ISSUE TITLE
Gracefully handle Ωedit libc.so link failures

### ISSUE THREAD

**Issue by scholarsmate** [apache/daffodil-vscode#383]
If Ωedit is being run on a Linux system that has a different libc.so than the system it was built on, we'll get a dynamic linking exception.  We should attempt to gracefully handle that exception and inform the user that Ωedit is incompatible with the system its being run on and will need to be built from source instead.

**Comment by scholarsmate** [comment]
> Could this be statically linked instead?

For most dependency libraries, yes, but not for GLIBC (it's basically the kernel).  Static linking in this case is strongly discouraged.  Building on Ubuntu 20.04 LTS is a reasonable choice (and what we went with in Ωedit).  GLIBC maintains backward compatibility by versioning (via semver) its symbols.  Most Linux systems (e.g., not Alpine which uses musl libc) released on the past 2 years ought to work with binaries compiled on Ubuntu 20.04 LTS.

**Comment by scholarsmate** [comment]
Ubuntu 20.04 LTS (the OS used to build the Ωedit Linux binaries) uses glibc 2.31, released February 1, 2020.  If deployed on a Linux OS that has glibc 2.31 or greater ought to be compatible.

**Comment by Shanedell** [comment]
@scholarsmate Shouldn't this be more of an `omega-edit` thing not a `daffodil-vscode` thing?

**Comment by scholarsmate** [comment]
@Shanedell, yeah, now that the server management functions have been migrated over to Ωedit, it makes sense to have the Ωedit server management handle it.  We'll need to plum error propagation so that the front-end can inform the user of the incompatibility.

**Comment by Shanedell** [comment]
Closing this as this will be an `omega-edit` issue now.
