### ISSUE TITLE
Rework debugger backend

### ISSUE THREAD

**Issue by shanedell** [apache/daffodil-vscode#39]
Have the Daffodil debugger backend zip added to the VSIX and have the extension use this file instead of trying to download the zip file from the releases url of the repo

**Comment by jw3** [comment]
How do you envision supporting multiple Daffodil versions?

**Comment by jw3** [comment]
I'm just wondering if this PR simplifies Daffodil debugger development, but as a side effect also reduces some usability while debugging during schema development.  

Instead of removing the download capability intended for marketplace installs, could we just provide an improved method of installation for development environments?

**Comment by mbeckerle** [comment]
I have to say, I hoped to be able to use the debugger with various
different Daffodil versions for support reasons.

My needs can be accommodated, however, by just having 2 (or more) different
VSCode installs, each with a different debugger + daffodil combination.

At some point I'd like to see if the debugger "dap" interface can be
back-ported to Daffodil 2.7.0. or even 2.6.0. We even have customers on
2.4.0.

I expect the cybersecurity community that is deploying daffodil to "scrub"
data, will all have this sort of broad set of releases to support as an
issue.

E.g., I expect to deliver training on DFDL/Daffodil in January to a
user/customer community and by then I'd hope to be able to use the
debugger. That customer will be using Daffodil 2.7.0.

**Comment by jw3** [comment]
Up until this discussion I had been under the impression that there was value in conveniently running multiple versions of Daffodil in the IDE.  Pretty much like Mike described above.

I am not convinced that (1) users only want latest, or (2) it's acceptable to tell people to reinstall to get a different version, or that (3) the compiler should be distributed with the IDE, but I would like to get this moving forward.

So I'm good with taking the simple approach here and bundling the backend for the 1.0.0 version of the extension.  We only have a single supported Daffodil version at the moment anyways (3.1.0).

We do need to revisit this after 1.0.0 and address the lingering concerns.  I'll add a separate issue for that.
