### ISSUE TITLE
APP_CLASSPATH Length Issue

### ISSUE THREAD

**Issue by Shanedell** [apache/daffodil-vscode#431]
Currently the `APP_CLASSPATH` is set via one line that list all jars needed. However, when it comes to adding new Scala dependencies (eg like in the TDML PR), it can make this line very long. When the line is too long, at least in Windows, the script will fail to run.

So is there a way we can break up this one liner into multiple lines or make it so its not going to effect the script?

Ideas:

- @scholarsmate Did have an idea of creating a JAR that contains a manifest file whose `Class-Path` specifies the disk paths of all the jars. This way only that single JAR, with the manifest, would need to be added to the `APP_CLASSPATH`. Would this be a good solution?

Information:

- Tagging @stevedlawrence @mbeckerle @tuxji in case you guys have any input, since this maybe is something that happened in Daffodil as well.

**Comment by arosien** [comment]
I have tested the [classpath-jar solution provided by sbt-native-packager](https://www.scala-sbt.org/sbt-native-packager/recipes/longclasspath.html) at https://github.com/apache/daffodil-vscode/pull/253 and it seems to let the windows tests pass. I'll make a separate PR attached to this issue.
