### ISSUE TITLE
Incorrect intellisense suggestions triggered at the schema closing tag

### ISSUE THREAD

**Issue by rt320** [apache/daffodil-vscode#461]
Incorrect intellisense suggestions triggered at the schema closing tag.  When the cursor is positioned at the beginning of the schema closing tag '</xs:schema> and control space is entered, the intellisense results are generic alphabetic results (as of PR #458) instead of the results that should be supplied by the element completion function.

**Comment by scholarsmate** [comment]
This may be done.  Needs a final test.
