### ISSUE TITLE
LICENSE/NOTICE file in .vsix is not correct

### ISSUE THREAD

**Issue by stevedlawrence** [apache/daffodil-vscode#48]
The LICENSE file that goes in the .vsix is copied from the LICENSE file in the root of our repo, but technically these should be different.

The LICENSE file in the root or our repo should cover only the source code in the repo, which is currently does correctly.

But the LICENSE file in the distributed .vsix should cover things that are in the .vsix file. This includes everything in the main LICENSE file, but should also include license information bundled dependencies. This includes Daffodil and its LICENSE as well as license information from all the npm dependencies.

How to do this sanely is a big challenge, since we have hundreds of transitive npm dependencies.

**Comment by jw3** [comment]
The previous list was pulling in dev dependencies too, limiting to production reduces it by 95%.

`yarn license-checker --production`
