### ISSUE TITLE
Replace glob package

### ISSUE THREAD

**Issue by shanedell** [apache/daffodil-vscode#492]
The `glob` package isn't used to often. Also in later versions I believe it throws some unexpected errors. I think we can get rid of this package and use vanilla TypeScript code with recursion to replace it.

Places that currently use glob.

```txt
build/scripts/package.ts
src/tests/suite/index.ts
```

I believe some packages have it as a dependency but we want to remove it as a main dependency in our code base and make it so we don't rely on it.

**Comment by shanedell** [comment]
I am not sure how much this is needed. After looking over some things, glob seems to only be used by us for some scripting stuff. So it shouldn't be getting packaged in our releases.

@scholarsmate @mbeckerle @stevedlawrence @arosien @nlewis05 @stricklandrbls @NolanMatt @NolanMatt @michael-hoke @rthomas320 What does everyone think, should this still be done for 1.4.0 or is it non necessary to do?

**Comment by nlewis05** [comment]
> am not sure how much this is needed. After looking over some things, glob seems to only be used by us for some scripting stuff. So it shouldn't be getting packaged in our releases.

Would it be possible to document those unexpected errors in this ticket? If they seem to be specific to this package, then we can close the issue with those errors documented, and if they are because of something else within the extension, then at least we have that documented somewhere and investigate further.

**Comment by shanedell** [comment]
I am going to close this issue as I don't think it needs to be done. Also, documentation found at [Testing VSCode Extension](https://code.visualstudio.com/api/working-with-extensions/testing-extension#the-test-runner-script), setups up running the tests using glob so trying to remove it may cause issues trying to run tests. But this package is also a dev dependency so it never gets published into our extension and I can't completely what the issues were that I ran into before. But again I don't think we need to this unless we start running into issues causes strictly by having the glob package
