### ISSUE TITLE
Unintended log and heartbeat sharing when more than one DE is running

### ISSUE THREAD

**Issue by scholarsmate** [apache/daffodil-vscode#503]
Open a Data Editor on port 9000, then open another Data Editor on port 9001, and suddenly you'll notice that the heartbeats are both _saying_ that they are running on port 9001.  Also the logs are now all being written to the log file for 9001.  Both Data Editors appear to work just fine (they are communicating with their original servers), but the heartbeats and logs should be going into their respective locations.

**Comment by scholarsmate** [comment]
The bug was addressed by only allowing a single Data Editor to be running at one time.  We plan to allow multiple Data Editors to share one server instance in an upcoming release.

**Comment by stricklandrbls** [comment]
Closed with merge of #509
