### ISSUE TITLE
Name data editor tab according to the file name

### ISSUE THREAD

**Issue by arosien** [apache/daffodil-vscode#507]
Calling the tab "Data Editor" is confusing. All editors I know of put the filename in the tab, with the full path in the hover text. I imagine VS Code probably has some helpers for all of this.

**Comment by scholarsmate** [comment]
@arosien, I'm sure there is some easy way to do this, but I'm not finding any.

**Comment by scholarsmate** [comment]
Someone else is having the same issue I am: https://stackoverflow.com/questions/75181381/not-able-to-provide-tooltip-value-different-than-the-value-of-title-property-on.  Currently there are no answers.
