### ISSUE TITLE
Display themes don't change Data Editor background colors

### ISSUE THREAD

**Issue by lrbarber** [apache/daffodil-vscode#536]
Light themes are especially hard to read.

![3acb2279-0784-4a5e-ad15-bf3e01177ab8](https://user-images.githubusercontent.com/72564532/228274567-a7c59a1a-5e8e-4a21-b851-8cd0a2e19dc9.jpg)

**Comment by stricklandrbls** [comment]
After some feedback, there are some components that can be difficult to see, depending on which color theme the user is using. I have a commit that will change some component outlines to help make them generally more visible.
