### ISSUE TITLE
Setting of omega-edit port not working

### ISSUE THREAD

**Issue by Shanedell** [apache/daffodil-vscode#579]
Inside of `.vscode/launch.json` we are supposed to be able to set `dataEditor.omegaEditPort` to tell the dataEditor what port to use. However, this doesn't seem to be working as when I set this the in the `launch.json` I get a yellow squiggly line that says `Property dataEditor.omegaEditPort is not allowed.`. Then if I ignore that and set the port, the port specified is not used it just always go to `9000`.

This is fixed when:

- Setting `dataEditor.omegaEditPort` in the `.vscode/launch.json` does not show a yellow squiggly line any longer.
- The port specified by `dataEditor.omegaEditPort` is used when booting omega-edit.

**Comment by arosien** [comment]
The squiggly line can be addressed by specifying the omega edit property in the schema in a different way. Instead of
 `dataEditor.omegaEditPort`, use nested schema definitions `dataEditor` and `omegaEditPort`.

**Comment by Shanedell** [comment]
I believe @scholarsmate fixed the squiggly line in a recent PR. Then another PR I have out currently fixes the issue of the port value not being updated when set from the launch.json.
