### ISSUE TITLE
Search Prev/Next buttons not properly sync'ed with the Offset

### ISSUE THREAD

**Issue by scholarsmate** [apache/daffodil-vscode#584]
Open this repo's `package.json`, then `Search` for `Apache`, click the `Prev` and `Next` buttons and observe what's being scrolled to and what's being displayed in the `Offset` input box and see that they aren't matching up correctly.

**Comment by stricklandrbls** [comment]
Looks like there's an index lag with pressing the buttons and populating the `Offset`. The displayed search result is displaying `results[0]` but the `Offset` is `results[1]`. I'll get a fix for this.

---
Also FYI, the great people at Comcast were digging in my front yard, placing fiber cable. While doing so they cut my AT&T fiber line so I don't have internet at the moment for my CTC machine. It's not happy when trying to tether from my phone's data and I'm using a directional antenna to use the WiFi from a neighbor's house lol.
