### ISSUE TITLE
Add missing xs:restriction child elements

### ISSUE THREAD

**Issue by rthomas320** [apache/daffodil-vscode#587]
Add missing xs:restriction child elements:  xs:pattern, xs:totalDigits, xs:fractionDigits, and xs:enumeration

**Comment by hdalsania** [comment]
restriction element is available for SimpleType schema element. For example,

<xs:simpleType name="mountainbikesize">
  <xs:restriction base="xs:string">
    <xs:enumeration value="small"/>
    <xs:enumeration value="medium"/>
    <xs:enumeration value="large"/>
  </xs:restriction>
</xs:simpleType>
