### ISSUE TITLE
Add missing dfdl:property element

### ISSUE THREAD

**Issue by rthomas320** [apache/daffodil-vscode#588]
Add missing dfdl:property element.  Add the property element as a child to the dfdl:format element.

**Comment by hdalsania** [comment]
dfdl specification section 6.2, table 2 describes dfdl:format and dfdl: property elements. 

Here is the example, 

 <xs:annotation>
   <xs:appinfo source="http://www.ogf.org/dfdl/">
     <dfdl:format>
       <dfdl:property name='encoding'>utf-8</dfdl:property>
       <dfdl:property name='separator'>%NL;</dfdl:property>
     </dfdl:format>
   </xs:appinfo>
 </xs:annotation>
