### ISSUE TITLE
stopOnEntry doesn't seem to work

### ISSUE THREAD

**Issue by mbeckerle** [apache/daffodil-vscode#59]
I have set stopOnEntry to false, but the debugger still seemed to stop, not to parse the data.

**Comment by arosien** [comment]
@mbeckerle can you post the launch.json configuration you're using?

I also wonder if you have a breakpoint defined, and that's where the debugger is stopping, rather than the stopOnEntry flag being mistakenly honored.

**Comment by michael-hoke** [comment]
To add to what Adam wrote, if you want to use (only) his launch config, the entire launch.json file would look like this
`{
  "configuration": [
    {
      "request": "launch",
      "type": "dfdl",
      "name": "EDIFACT",
      "program": "/Users/arosien/nteligen/EDIFACT/src/main/resources/EDIFACT-SupplyChain-D03B/EDIFACT-SupplyChain-Messages-D.03B.xsd",
      "data": "/Users/arosien/nteligen/EDIFACT/src/test/resources/EDIFACT-SupplyChain-D03B/TestData/INVOIC_D.03B_Interchange_with_UNA.txt",
      "debugServer": 4711,
      "infosetOutput": {
        "type": "file",
        "path": "${workspaceFolder}/infoset.xml"
      },
      "trace": true,
      "stopOnEntry": false,
      "useExistingServer": true,
      "openHexView": false,
      "openInfosetView": false,
      "openInfosetDiffView": false,
      // "daffodilDebugClasspath": "/Users/arosien/nteligen/ethernetIP/src/main/resources",
      // "daffodilDebugClasspath": "/Users/arosien/nteligen/ethernetIP/target/dfdl-ethernetip-1.2.0.jar"
    }
  ]`

**Comment by scholarsmate** [comment]
Where are we with issue?

**Comment by arosien** [comment]
> Where are we with issue? Should this be closed?

I think we should close and @mbeckerle can reopen if he can provide reproduction info.

**Comment by mbeckerle** [comment]
I don't recall experiencing this with 1.1.0 release. SO you can close it.
