### ISSUE TITLE
Add missing escapeScheme element and attributes

### ISSUE THREAD

**Issue by rthomas320** [apache/daffodil-vscode#591]
The dfdl:escapeScheme element is missing along with the following attributes:
dfdl:escapeKind
dfdl:escapeCharacter
dfdl:escapeBlockStart
dfdl:escapeBlockEnd
dfdl:escapeEscapeCharacter
dfdl:extraEscapedCharacters
dfdl:generateEscapeBlock
dfdl:escapeCharacterPolicy
Add escapeScheme as a child element to defineEscapeScheme element

**Comment by hdalsania** [comment]
dfdl specification section 6.2, table 2 describes dfdl:defineEscapeScheme and dfdl: escapeScheme elements.

Here is the example,

<xs:annotation>
   <xs:appinfo source="http://www.ogf.org/dfdl/">
     <dfdl:defineEscapeScheme name="myEscapeScheme">
       <dfdl:escapeScheme escapeKind="escapeCharacter" escapeCharacter='/' />    
     </dfdl:defineEscapeScheme>
   </xs:appinfo>
 </xs:annotation>
