### ISSUE TITLE
Create GUI editor for TDML files

### ISSUE THREAD

**Issue by michael-hoke** [apache/daffodil-vscode#595]
We should be able to open a TDML file and have the language identified as TDML. We should then be able to move TDML items from the command palette that are locked to the DFDL language into the new TDML language.

**Comment by michael-hoke** [comment]
See here for some naming suggestions to keep in mind when rebuilding TDML support. Also keep in mind that we are starting off implementing the bare minimum of the TDML spec, so we should try to avoid potentially conflicting names of potential future features.

https://github.com/apache/daffodil-vscode/pull/625#discussion_r1187619693

**Comment by michael-hoke** [comment]
- Add 'none' back in as an option for tdmlAction. Keep 'generate' as the default option.
    - Is this right? Is there a scenario where turning off TDML generation makes sense? If there isn't, then leave 'none' out.
- Make tdmlConfig a mandatory part of the launch config
- Change the default location of the generated TDML file to be in /tmp (or OS alternative)
- Add a new command to copy the TDML file from /tmp to a user-defined location
- Remove the Generate TDML command from the command palette
- Create a new 'TDML' language that inherits from XML (should be set up similarly to dfdl language).
- Move Append TDML command to the new TDML language
- Add a command to create zip file in TDML language

**Comment by michael-hoke** [comment]
If time permits, explore the possibility of using the Selenium tests for the new GUI

**Comment by michael-hoke** [comment]
Current issue that we are running into is that when we try to use HTML to render a GUI, we are unable to import anything from the WebView we are using to produce the HTML. Our best guess at the moment is that whatever is responsible for packaging up dependencies to be used dynamically during runtime is not doing it correctly. Second best guess is that we are importing using the wrong path, but the files we are pointing to exist on disk in the location we expect them to exist (might be related to index.d.ts or .jms missing when expected).

We used a guide (https://timheuer.com/blog/resx-editor-for-visual-studio-code/) to base our initial version of a WebView on, but that wasn't working due to the import issue. We tried using that extension (https://marketplace.visualstudio.com/items?itemName=TimHeuer.resx-editor) and it works fine. However, when we try to use the same methods in the DFDL extension, it does not.

**Comment by NolanMatt** [comment]
to add to what Mike said, if we remove all imports from our webview.js file, then it will function as expected, but obviously doesn't do anything because its just dispalying raw hardcoded html at that point since we can't do any xml manipulation without importing xml libraries.

This applies to any import that is not local to our code (ie we can import the tdmlXmlUtils file, but we cannot import anything from a library)

**Comment by hdalsania** [comment]
This feature is implemented and merged with #936
