### ISSUE TITLE
Document how to change the Ωedit port

### ISSUE THREAD

**Issue by scholarsmate** [apache/daffodil-vscode#597]
@Shanedell recently merged a PR for allowing the user to change the port for the Ωedit server.  This ticket is to make sure the documentation is updated to show how to use that setting.

**Comment by Shanedell** [comment]
This can be closed. I added the [Data Editor Launch Settings Section](https://github.com/apache/daffodil-vscode/wiki/Apache-Daffodil%E2%84%A2-Extension-for-Visual-Studio-Code:-v1.3.0#data-editor-launch-settings) to the 1.3.0 wiki page.
