### ISSUE TITLE
Add Language Extension

### ISSUE THREAD

**Issue by jw3** [apache/daffodil-vscode#6]
We use the built-in XML language currently, which allows the DFDL XSD to be debugged, but also applies to other XML, like an infoset file.

Adding a DFDL extension should give ability to express schemas more precisely and will also support editing and other needs.

Imported from https://github.com/jw3/example-daffodil-vscode/issues/42

**Comment by Shanedell** [comment]
This was done in a PR for 1.1.0

**Comment by stevedlawrence** [comment]
For tracking purposes, can you link to the PR that merged this? I guess we forgot to add `Closes #XYZ` to the commit that fix this.
