### ISSUE TITLE
1.3.0-rc1 - LICENSE/NOTICE

### ISSUE THREAD

**Issue by Shanedell** [apache/daffodil-vscode#600]
This issue comes from @stevedlawrence in the [vote thread for 1.3.0-rc1](https://lists.apache.org/thread/r2grf2lm3ox6m33g8n6s2gf65wn2lcrq). The issue is described below:

```txt
[FAILED] src and binaries include correct LICENSE/NOTICE
- build/extension.webpack.config.js is MIT licenses but is not in the
   main LICENSE file. It is in build/package/LICENSE file, but I think
   that is incorrect since this file does not end up in the vsix file?

- The following yarn dependencies are listed as production dependencies but
   are not listed in the build/package/LICENSE file. They are category
   A so are okay but need to be listed:

    BSD-3-Clause
    - ieee754@1.2.1
    ISC
    - split2@4.2.0
    MIT
    - abort-controller@3.0.0
    - atomic-sleep@1.0.0
    - base64-js@1.5.1
    - buffer@6.0.3
    - event-target-shim@5.0.1
    - events@3.3.0
    - fast-redact@3.1.2
    - is-fullwidth-code-point@3.0.0
    - on-exit-leak-free@2.1.0
    - pino-abstract-transport@1.0.0
    - pino-std-serializers@6.2.0
    - pino@8.11.0
    - process-warning@2.2.0
    - process@0.11.10
    - quick-format-unescaped@4.0.4
    - readable-stream@4.3.0
    - real-require@0.2.0
    - safe-stable-stringify@2.4.3
    - sonic-boom@3.3.0
    - thread-stream@2.3.0

- The following dependencies are listed in build/package/LICENSE or
   biuld/package/NONOTICE but are not actual production dependencies
   and should not be listed:

   - @cspotcode/source-map-support
   - @jridgewell/resolve-uri
   - @jridgewell/sourcemap-codec
   - @jridgewell/trace-mapping
   - @tsconfig/node10
   - @tsconfig/node12
   - @tsconfig/node14
   - @tsconfig/node16
   - acorn
   - acorn-walks
   - arg
   - create-require
   - diff
   - fsevents
   - is-fullwidth-code-point
   - make-error
   - ts-node
   - v8-compile-cache-lib
   - yn

- The build/production/LICENSE file lists omega-edit-grpc-server-*.zip
   but that ZIP is no longer in the vsix file, the zip is packages
   uncompressed

- The build/package/ licenes files mention akka, though that has been
   replaced with pekko

- The following omega-edit or daffodil debugger jar dependencies are
   not mentioned in the build/package/* files

   Daffodil Debugger:
   - com.sun.istack.istack-commons-runtime-2.21.jar
   - com.sun.istack.istack-commons-tools-2.21.jar
   - com.sun.xml.bind.external.rngom-2.2.11.jar
   - com.sun.xml.bind.jaxb-impl-2.2.11.jar
   - com.sun.xml.dtd-parser.dtd-parser-1.1.jar
   - com.sun.xsom.xsom-20140925.jar
   - javax.activation.activation-1.1.1.jar
   - javax.xml.bind.jaxb-api-2.2.12-b140109.1041.jar
   - org.apache.ant.ant-1.7.0.jar
   - org.apache.ant.ant-launcher-1.7.0.jar
   - org.glassfish.jaxb.codemodel-2.2.11.jar
   - org.glassfish.jaxb.jaxb-core-2.2.11.jar
   - org.glassfish.jaxb.jaxb-xjc-2.2.11.jar
   - org.glassfish.jaxb.txw2-2.2.11.jar
   - relaxngDatatype.relaxngDatatype-20020414.jar

   Omega Edit
   - ch.qos.logback.logback-classic-1.3.5.jar
   - ch.qos.logback.logback-core-1.3.5.jar
   - com.google.api.grpc.proto-google-common-protos-2.9.0.jar
   - org.checkerframework.checker-qual-3.12.0.jar
   - org.parboiled.parboiled_2.13-2.4.1.jar
```

This should be address in the next release canidate for 1.3.0.

**Comment by Shanedell** [comment]
@stevedlawrence for comment:

```txt
- build/extension.webpack.config.js is MIT licenses but is not in the
   main LICENSE file. It is in build/package/LICENSE file, but I think
   that is incorrect since this file does not end up in the vsix file?
```

I think I get what you are saying. The line for `build/extension.webpack.config.js` should be taken out of `build/package/LICENSE` and put in the main `LICENSE` file correct? You are correct that `build/extension.webpack.config.js` doesn't get copied into the VSIX file.

**Comment by Shanedell** [comment]
@stevedlawrence I also saw the minor issue about `xs` prefix. The intellisense should work on schemas that don't use the `xs` prefix. Eg `edifact`.

One reason it may not work is `dfdl` may not be your selected language for the schema. For example, locally for `edifact` for me it was defaulting to `XML` as the detected language. In this case dfdl intellisense would not work. After setting the language to `dfdl` the intellisense was now working for me. Can you see if this was possibly the issue you ran into as well?

**Comment by stevedlawrence** [comment]
It seems to be working now. The language was DFDL when I started it, so 
maybe it fixed itself.

I've also found some cases where unclosed sequence tags causes 
autocompletions later in the schema to fail to suggest the correct 
things. Maybe I was actually running into something like that and just 
thought it was an xs: issue and didn't realize the invalid XML.

I think this was likely just user error on my part.

**Comment by Shanedell** [comment]
@stevedlawrence Gotcha, do I have the idea correct on `build/extension.webpack.config.js`? It needs to be in the root LICENSE not the VSIX one, since its not included in the VSIX?

**Comment by stevedlawrence** [comment]
Yep, that's right

**Comment by Shanedell** [comment]
@stevedlawrence for `com.sun.xsom.xsom-20140925.jar` is that compatible? It uses `COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL)Version 1.1 License` which is listed here https://www.apache.org/legal/resolved.html#weak-copyleft-licenses, was sure since its under the `"WEAK COPYLEFT" LICENSE"` if that means it can be used or not since its not listed under the strickly cannot be used.

**Comment by stevedlawrence** [comment]
CDDL and other "weak copyleft" licenses are fine when included in binary form like we do, but it's recommended to explicitly mention it where someone is likely to see it. For example, the Daffodil CLI distributes binary jars under CDDL and MPL, both of which are weak copyleft, so we add a blurb in the CLI readme:

https://github.com/apache/daffodil/blob/main/daffodil-cli/README.md#license

**Comment by Shanedell** [comment]
@stevedlawrence Gotcha thank you. I see we did in this project for a couple as well. Any advice on  https://github.com/java-schema-utilities/relaxng-datatype-java since it doesn't have one, should we try to get remove it somehow?

**Comment by stevedlawrence** [comment]
For relaxng-datatype-java, the pom.xml claims its "BSD": https://github.com/java-schema-utilities/relaxng-datatype-java/blob/master/pom.xml#L39, though which variant is unclear...

There is this issue that asks for clarification [java-schema-utilities/relaxng-datatype-java#1]( https://togithub.com/java-schema-utilities/relaxng-datatype-java/issues/1) and claims it's BSD-3, but I don't see where that is coming from, and a response questions that, so it's not clear. Might need some more digging to figure it out.

**Comment by Shanedell** [comment]
Gotcha thank you.

**Comment by Shanedell** [comment]
@stevedlawrence It looks like that comments says that its in a different repo. Seem possible it could be this repo is at https://github.com/relaxng/jing-trang. Would we use that [license](https://github.com/relaxng/jing-trang/blob/master/copying.txt) then or not?

**Comment by stevedlawrence** [comment]
Yeah, doing a diff of the datatype directories in the different repos shows they're pretty much the same. It looks like they were originally added to the jing-trang repo here:

https://github.com/relaxng/jing-trang/commit/5df37ac9869d4fa1cc50372effce275ddc551592

And we can see that same jclark person updated the copying.txt file to BSD-3 here:

https://github.com/relaxng/jing-trang/commit/cdaaa25a4ec3f37a809b3a84cc198b4e84ade1e3

So I think it's safe to assume the code they added to the jing-trang repo is licensed under the license you mentioned, and thus so is the code in the java-schema-uitils repo since it is not substantially different.
