### ISSUE TITLE
TDML configuration causing server timeout issue when running from launch.json

### ISSUE THREAD

**Issue by nlewis05** [apache/daffodil-vscode#622]
With the following configuration:
``` 
"tdmlConfig": {
 "action": "none",
 "name": "${command:AskForTDMLName}",
 "description": "${command:AskForTDMLDescription}",
 "path": "${command:AskForTDMLPath}" },
```

The debugger is continuing to ask for TDML configurations even when the action is "none"
![image](https://user-images.githubusercontent.com/131286323/236509303-7a0ef691-ca19-4265-a197-7c429192a253.png)

If the configuration are not given within a time limit, the debugger will terminate and crash.

![image](https://user-images.githubusercontent.com/131286323/236509451-9e16e5ce-1134-405c-8a8e-a6413106dcf5.png)

When this configuration was used:
```
           "tdmlConfig": {
                "action": "none",
                "name": "tdml1",
                "description": "tdml1",
                "path": "${workspaceFolder}/target/foo.tdml"
            },
```
The debugger will continue to run and not ask for the TDML configurations because they are already provided.

**Comment by Shanedell** [comment]
I believe the fix for this is adding an else to if that checks for certain actions eg:

```ts
if (
    config?.tdmlConfig?.action === 'generate' ||
    config?.tdmlConfig?.action === 'append' ||
    config?.tdmlConfig?.action === 'execute'
) {
    ...
} else {
    // either action is 'none' or bad action provided don't prompt
    config.tdmlConfig.name = ''
    config.tdmlConfig.description = ''
    config.tdmlConfig.path = '' 
}
```

This will make sure when the action is 'none' or not a good action the user won't get prompted.
