### ISSUE TITLE
.vscode/launch.json is not strict JSON

### ISSUE THREAD

**Issue by scholarsmate** [apache/daffodil-vscode#635]
Cannot have a this comment block:
https://github.com/apache/daffodil-vscode/blob/main/.vscode/launch.json#L1

Also cannot have trailing commas in arrays like we have here:
https://github.com/apache/daffodil-vscode/blob/main/.vscode/launch.json#L62

**Comment by nlewis05** [comment]
This issue correlates to whenever you "Add a configuration" either through "Run > Add Configuration" or if you are in the Run and Debug section of vscode and add configuration from the drop down or hit the cog wheel. I'm not sure where it is creating this launch.json from and how it is populating this default configuration. This is what it looks like when created:
![image](https://github.com/apache/daffodil-vscode/assets/131286323/e7b7cf98-125e-4f5c-aa94-27ce095bbb9a)

The issues lie with the comments at the top which invalidates the json, and once this file has been created, you are no longer able to open it with the launch config wizard as show below:
![image](https://github.com/apache/daffodil-vscode/assets/131286323/4c145d08-e8e0-4a26-b56b-18c9bbc89b34)

Once these comments are removed,
![image](https://github.com/apache/daffodil-vscode/assets/131286323/b07e176a-6620-4510-8866-7ead0b7fbbc3)

You can then open the launch config wizard again:
![image](https://github.com/apache/daffodil-vscode/assets/131286323/0da89369-d4b2-4f0d-aceb-fc40913127ed)

**Comment by arosien** [comment]
According to https://github.com/microsoft/vscode/issues/162434 we can use the [jsonc parser](https://www.npmjs.com/package/jsonc-parser) instead of the built-in JSON parser to handle JSON with comments.
