### ISSUE TITLE
Consistently name the project in the documentation

### ISSUE THREAD

**Issue by arosien** [apache/daffodil-vscode#65]
The name of the project is not consistent throughout the Github site:
- About: "Apache Daffodil VSCode"
- "VS Code Daffodil Debug"

I think the project should be called "Apache Daffodil VS Code Extension".
- "VS Code" is the way Microsoft writes the name of the editor.
- The extension is more than just the debugger, so just call it an extension.

**Comment by jw3** [comment]
#24 is related and can be resolved at the same time.

**Comment by Shanedell** [comment]
I can work on this which do we prefer `VSCode` or `VS Code`?

**Comment by arosien** [comment]
> I can work on this. The other extension from Apache uses `VSCode` so that is what I will go with unless advised otherwise

"VS Code" is the way Microsoft writes the name of the editor.
