### ISSUE TITLE
Store and Link Local Font and Icon for DataEditor

### ISSUE THREAD

**Issue by stricklandrbls** [apache/daffodil-vscode#661]
## Issue
There have been quite a few UI discrepancies for the Data Editor which all depend upon which system font that VSCode decides to implement as the `monospace` or `var(--vscode-font-family)` CSS properties / attributes.

#### Current Discrepancy
Currently, HTML hex codes are used to represent icons in the Data Editor without importing images. For example, `&#x1F4BE;` and `&#x1F4C1;` will display on this webpage as <span>&#x1F4BE;</span> and <span>&#x1F4C1;</span>, respectively. Likewise for Mac OS users.

However, on my _Ubuntu 22.04.2 LTS_ desktop the icons are represented as <span>&#9647;</span> due to the system font that I have set.

![Image](https://github.com/apache/daffodil-vscode/assets/30351915/2f837890-f02b-4b90-be5d-a2604a94b512)
<sup>Reference Image.</sup>

## Solution
Packaging a universal font, and/or icon pack, then linking these into the Data Editor will solve this. _Although_, it will come at the expense of a package size increase of the total size of the font / icon package.

**Comment by scholarsmate** [comment]
The Google Material Symbols and Icons would be a good fit, and they are Apache licensed.

See: https://fonts.google.com/icons

Google also has a nice collection of monospace fonts.

https://fonts.google.com/?category=Monospace

Of these fonts, my preference is Cousine:

https://fonts.google.com/specimen/Cousine?category=Monospace&preview.text=1234567890

**Comment by stricklandrbls** [comment]
@stevedlawrence VSCode comes with a package (codeicon) that can be added via `yarn` or `npm` but the icon set was pretty limited and, for some reason, difficult to implement in purely HTML based WebViews.

@scholarsmate and I initially tried adding the package and using the icons but the HTML was never able to render the iconset in our WebView. We immediately scraped the idea and moved on without much research as to why.

**Comment by scholarsmate** [comment]
@stricklandrbls the binary font files are failing the RAT check.  We might want install the fonts at build time rather than have them checked in.

**Comment by stricklandrbls** [comment]
> @stricklandrbls the binary font files are failing the RAT check. We might want install the fonts at build time rather than have them checked in.

Yeah I've got the `webpack.config.js` to use the `CopyPlugin` to take care of that but I am still unable to figure out the constant failures when running the `package.json` script for _webpacking_ the svelte directory.

It's almost as if it's not running the correlating to the correct config file because the error output descriptions referencing options that aren't even specified anywhere in the project.

I'm thinking maybe a path resolution is getting messed up and it's trying to compile modules from `node_modules`? Not sure but still looking into it.

**Comment by stevedlawrence** [comment]
> @stricklandrbls the binary font files are failing the RAT check. We might want install the fonts at build time rather than have them checked in.

It's fine to add an exclude entry in `project/Rat.scala` if a file cannot include a license that Rat can find, as long as it has an ASF compatible license. In fact, I think this is probably preferable since there is a more obvious record of the file in the source.  Please also do not forget to update the LICENSE/NOTICE files to mention the font.

**Comment by stricklandrbls** [comment]
Closes by #725
