### ISSUE TITLE
Command Palette context sensitivity is being over-used

### ISSUE THREAD

**Issue by mbeckerle** [apache/daffodil-vscode#674]
Using 1.3.0-RC3

To find the launch configuration wizard, you have to NOT be in an execution context. Like you cannot be partway through debugging. 

You have to click right on the right part of a schema _when not debugging_, then choose command palette from the menu. Then one of the choices is the launch config wizard. 

But if you are finished learning something using the debugger, just haven't hit the stop button yet. You go over to the editor for the schema file and click right,... launch wizard is ... not available to select. It's not there and greyed out, it's not even there. 

This is just bad. The right thing here is to have a menu with all the commands in it, with the ones that are not context relevant greyed out. 

But I claim this launch wizard should NOT be greyed out, or unavailable in this context anyway. Why shouldn't I be able to mess with the launch configuration, tweek it, and then hit the stop button on the prior debugging, or even continue the prior debugging to learn a bit more. There is no reason for this modality.

**Comment by shanedell** [comment]
I think this makes sense to me, so you are saying make the launch wizard always available? I am onboard with that because updating the launch.json while a debug is running shouldn't break anything as the config is already parsed. You are correct that currently it is only available when you aren't debugging, it should be greyed out not completely removed so that would be an issue. However, this will not matter if we make it always available.

**Comment by shanedell** [comment]
Is this something that should be in 1.3.0 or do you think 1.3.1 is okay?

**Comment by shanedell** [comment]
@mbeckerle Along with this do you think `hexview.display`, `infoset.display` and `infoset.diff` should always be available on debug mode? Currently it will only display in debug and file ends with `.dfdl.xsd` but some schemas just had `.xsd` so wasn't sure.

**Comment by mbeckerle** [comment]
This can be fixed in a post 1.3.0 release.

I like user interfaces that implement the Apple UI style guide principles: Users should not have to remember anything. They should be able to find and choose things from menus. Grey logic tells users when things are available or not based on context. But the menu contents shouldn't be changing/shifting. 

I'm not sure why everything in vscode seems tied to the command palette. You have to know to open that to find almost anything.

**Comment by shanedell** [comment]
@mbeckerle So there should also be icons in the top right corner. But yeah everything is tied to the command palette for vscode so clicking these icons is basically the same as running the command palette. That is why certain things in the command palette will not show up in certain cases.
