### ISSUE TITLE
launch config strange by-hand fixups required to make it work

### ISSUE THREAD

**Issue by mbeckerle** [apache/daffodil-vscode#675]
Testing 1.3.0-RC3

I created a launch config using the wizard. 

When I run it, I'm prompted that the infoset output type must be "file" with a little blocking dialog. 
I look at that by hand, and it contains "console", so I edit it to "file". Things now work. 

After a bit, I decide to make a new launch configuration. So I activate the launch config wizard again. I change it to new config, which is great because it looks like it will keep the existing settings, but creates a new configuration from them.
It does keep the Debug Classpath, but I did have to re-enter the schema file again, and the data file.  

However, when I run it, I'm prompted with a little blocking dialog that the tdmlConfig action must be "generate",... or a couple other options. 

This is from the new configuration just created. Note the action is empty string, and the others are "undefined"
```
            "tdmlConfig": {
                "action": "",
                "name": "undefined",
                "description": "undefined",
                "path": "undefined"
            }
```

My prior working launch configuration has:
```
            "tdmlConfig": {
                "action": "generate",
                "name": "null",
                "description": "null",
                "path": "null"
            },
```
Note the "null" not "undefined". 

I edited my new configuration to have "generate" for the action, and the configuration then works. 

These hand correction steps should not be needed.

**Comment by shanedell** [comment]
@mbeckerle would you like this in 1.3.0 or 1.3.1?

**Comment by shanedell** [comment]
@mbeckerle I can recreate the issue with `tdmlConfig` however I can't recreate the issue you were having with `infosetOutput`.

**Comment by mbeckerle** [comment]
I do think the launch config dialog has to work right for 1.3.0.  So this issue and the fact that the launch-config wizard GUI is illegible are pretty important to fix. 

RE: infosetOutput. I set the infosetOutput to use a /tmp/infoset.out.xml, and that's a file, so requires the file setting. What's curious is that it was somehow remembering this despite my blowing away the launch.json file. When I recreate a new launch.json, it somehow has "console" as the output type, but it has somehow remembered my /tmp/infoset.out.xml file location, and that's inconsistent with "console" setting.

**Comment by shanedell** [comment]
@mbeckerle Okay do those paths looked that pad all the time or only for longer paths?

Also it shouldn't remember that, when adding a new launch.json and you add a new one the default should be:

```json
{
    "type": "console",
    "path": "${workspaceFolder}/infoset.xml"
}
```
this is a bug because it should `file` but still shouldn't remember a previous path.

**Comment by shanedell** [comment]
@mbeckerle Does just updating `action` to be `generate` fix the error? Or will keeping the `null` in there break something? (it shouldn't). The main issue should be with the action being blank which is an easy fix because then whatever is set for the other items should be thrown out if the `action` is set to something other than the 3 supported options.
