### ISSUE TITLE
Debugger issues in Java 17

### ISSUE THREAD

**Issue by shanedell** [apache/daffodil-vscode#676]
As noted by @mbeckerle inside of issues:

- https://github.com/apache/daffodil-vscode/issues/648
- https://github.com/apache/daffodil-vscode/issues/649

So things are not working properly when using Java 17. This issue is for looking into why that is.

**Comment by arosien** [comment]
Looks like certain reflection isn't allowed by default in JDK 17: https://docs.oracle.com/en/java/javase/17/migrate/migrating-jdk-8-later-jdk-releases.html#GUID-7BB28E4D-99B3-4078-BDC4-FC24180CE82B

I'll try out the use of `--add-opens` as a workaround.

**Comment by arosien** [comment]
I've recreated the JVM reflection issue mentioned in #649 when generating a TDML file.
