### ISSUE TITLE
Allow setting the log level of the debugger

### ISSUE THREAD

**Issue by shanedell** [apache/daffodil-vscode#679]
> Another rough spot is that there is so much terminal output that it's hard
to find the error messages in there. Is there a way to set the debug level
to ERROR so that the info and debug messages aren't displayed? I had to
search for ".error" to find the assertion failure statement (which has
java.lang.error as a prefix of the message).

Mentioned by @mbeckerle in his vote 1.3.0-rc4.

There should an item to configure in the launch.json, such as `debuggerLogLevel`, that allows you to set the level the debugger will log too. This value then gets sent to the debugger on launch and based on the value provided it will log to that level.

**Comment by arosien** [comment]
The default level should also be set to INFO (vs. DEBUG).

**Comment by shanedell** [comment]
There are two ways this can be done:

- Environment variable being set when the debugger is ran that the `logback.xml` which use to set the level.
- Scala code parses the config value and then sets it programmatically within the code

@mbeckerle @stevedlawrence @arosien would there a preferred way to do this?
