### ISSUE TITLE
Upgrade to daffodil 3.5.0

### ISSUE THREAD

**Issue by shanedell** [apache/daffodil-vscode#680]
- Upgrade debugger to use daffodil version 3.5.0

**Comment by arosien** [comment]
@mbeckerle @stevedlawrence did the package names of various classes change from the 3.4.0 to 3.5.0 release, or some aliasing isn't working anymore? Imports such as `import org.apache.daffodil.debugger.Debugger` now have to be explicit like `import org.apache.daffodil.runtime1.debugger.Debugger`.

**Comment by arosien** [comment]
> @mbeckerle @stevedlawrence did the package names of various classes change from the 3.4.0 to 3.5.0 release, or some aliasing isn't working anymore? Imports such as `import org.apache.daffodil.debugger.Debugger` now have to be explicit like `import org.apache.daffodil.runtime1.debugger.Debugger`.

@mbeckerle @stevedlawrence ☝️

**Comment by stevedlawrence** [comment]
Yes, some package names were changed to support OSGI. See DAFFODIL-2683.

**Comment by arosien** [comment]
> 2683

https://issues.apache.org/jira/browse/DAFFODIL-2683
