### ISSUE TITLE
Publish to marketplace

### ISSUE THREAD

**Issue by jw3** [apache/daffodil-vscode#7]
Automated publishing of releases to VS Code marketplace.

Normally you would configure the publishing through https://marketplace.visualstudio.com/manage but this depends on the ASF procedures for publishing.

Blocked by #3 which updates the publisher and other details for the Apache project.

Original issue https://github.com/jw3/example-daffodil-vscode/issues/26

**Comment by stevedlawrence** [comment]
Here's an INFRA issue about other Apache Netbeans publishing to the marketplace:

https://issues.apache.org/jira/browse/INFRA-21017

So `asf` probably is the correct publisher ID, though it sounds like we'll need to open infra tickets for individual Daffodil devs to get contributor access to publish to the marketplace. Once users get that access, we'll want to document the process to publish packages in the release workflow page.

**Comment by Shanedell** [comment]
@stevedlawrence I have published the extension to this VS Code Marketplace so this should be closed correct? (https://marketplace.visualstudio.com/items?itemName=ASF.apache-daffodil-vscode)

**Comment by stevedlawrence** [comment]
Any idea why the breadcrumb at the top of that page says "Snippets"?

Can you update the [Release Workflow](https://cwiki.apache.org/confluence/display/DAFFODIL/Release+Workflow) "Promoting to Final Release" section to include detailed instructions on how to get access and upload the vsix artifact.

Maybe we should also add a tab next to "Download" (similar to Daffodil's Maven/SBT/DNF tabs) that describes how to install the extension from withing VS Code? Maybe something similar to what the market place describes in the "Installation" section (i.e. Open VS Code, press Ctrl-P, and run "ext install ASF.apache-daffodil-vscode")

Also, I've added a tweet for this on the @ApacheDaffodil twitter.

**Comment by Shanedell** [comment]
@stevedlawrence Would this be okay to close as I updated the [Release Workflow](https://cwiki.apache.org/confluence/display/DAFFODIL/Release+Workflow) with a new subsection for publishing the VS Code extension.

**Comment by stevedlawrence** [comment]
Yep, I think this is good to close. I've also merge https://github.com/apache/daffodil-site/pull/93 to add marketplace instructions.
