### ISSUE TITLE
Selection sticks when scrolling

### ISSUE THREAD

**Issue by scholarsmate** [apache/daffodil-vscode#731]
See animation below.

![Screen_Recording_2023-08-03_at_9_06_37_PM_AdobeExpress](https://github.com/apache/daffodil-vscode/assets/2205472/99551b04-fe28-4fb5-aa14-ad89555dd353)

**Comment by stricklandrbls** [comment]
Ah yeah we shouldn't be able to scroll at all when a selection is made.
