### ISSUE TITLE
Launch configuration with useExistingServer true shouldn't try to launch debugger backend

### ISSUE THREAD

**Issue by arosien** [apache/daffodil-vscode#744]
I am running off of main, commit 43672e8c, and if I have a launch configuration with `"useExistingServer": true`, my expectation is that the extension will **not** try to launch the debugger backend itself, but will attempt to talk to a (manually launched) backend on the `debugServer` port (4711 by default). However the extension tries to launch the backend (it fails because I didn't package the backend locally):
```
export DAFFODIL_DEBUG_CLASSPATH=/Users/arosien/nteligen/ethernetIP/target/dfdl-ethernetip-1.2.0.jar
export DAFFODIL_DEBUG_LOG_LEVEL=INFO
export DAFFODIL_DEBUG_LOG_FILE=/tmp/daffodil-debugger.log
/Users/arosien/nteligen/daffodil-vscode/daffodil-debugger-3.5.0-1.3.0/bin/daffodil-debugger --listenPort 4711
➜  sampleWorkspace export DAFFODIL_DEBUG_CLASSPATH=/Users/arosien/nteligen/ethernetIP/target/dfdl-ethernetip-1.2.0.jar
➜  sampleWorkspace export DAFFODIL_DEBUG_LOG_LEVEL=INFO
➜  sampleWorkspace export DAFFODIL_DEBUG_LOG_FILE=/tmp/daffodil-debugger.log
➜  sampleWorkspace /Users/arosien/nteligen/daffodil-vscode/daffodil-debugger-3.5.0-1.3.0/bin/daffodil-debugger --listenPort 4711
zsh: no such file or directory: /Users/arosien/nteligen/daffodil-vscode/daffodil-debugger-3.5.0-1.3.0/bin/daffodil-debugger
```
(terminal output)

**Comment by shanedell** [comment]
@arosien Are you sure chose the appropriate launch configuration and are synced with main? Whenever I have `"useExistingServer": true` I am not seeing this issue.

**Comment by arosien** [comment]
Hmm, I may have had a bad local install and I can't reproduce this, so closing. Sorry!

But I see you filed #747, so something good came out of it.
