### ISSUE TITLE
Classpath shouldn't be hardcoded in the template

### ISSUE THREAD

**Issue by jw3** [apache/daffodil-vscode#75]
Here is the offending line
https://github.com/apache/daffodil-vscode/blob/main/server/core/src/templates/bash-template#L369

SBT Native Packager normally generates that for the release based on the dependencies, we do not want to be responsible for that process.

The reason we provide a template is to provide the schema extension classpath from the VS Code side.  That should be able to be injected into the generated template rather than specifying a full override of the template.

**Comment by stevedlawrence** [comment]
You may consider an approach similar to what that Daffodil CLI does: https://github.com/apache/daffodil/tree/main/daffodil-cli/src/templates

Those templates are a lot less complex so a bit easier to understand. And I assume this debug tool is mostly going to be run by the debugger and not directly run, so may not need all the features that the default template provides.
