### ISSUE TITLE
Highlighting of bytes/bits to track the infoset when debugging

### ISSUE THREAD

**Issue by nlewis05** [apache/daffodil-vscode#790]
When parsing, placing cursor on a specific info set element should display the bits corresponding to it in the editor (or hex/bits display), and vice versa. We want to show where the parser is in the editor in the bits

**Comment by stricklandrbls** [comment]
@shanedell @shanedell @nlewis05 @hdalsania @lrbarber 

As mentioned in [this comment](https://github.com/apache/daffodil-vscode/issues/905#issuecomment-1851024517), I've got the data editor to a point where it can receive the `daffodil.data` messages from stepping through the debugger. Now though, with messages now flowing between the three extension components (DFDLDebugger, Data Editor UI, and Data Editor WebviewPanel), there's a quite a few different "message" structures floating around between DFDL debug events, Data Editor <-> Omega Edit messages, and not the DFDL Debugger -> Data Editor events.

For instance, these are the current message structures:

<details><summary><b>DFDL Debugger Messages</b></summary>

```ts
export const msgTypeString = 'daffodil.[some_event_type]'
export interface MsgTypeStructure {
     someField: any
}
```

</details>

<details><summary><b>Data Editor UI / Extension Messages</b></summary>

```ts
export enum MessageCommand {
    /* a bunch of message types */
}
/* Type alias to conform to the WebviewPanel.postMessage() */
export type EditorMessage = {
     command: MessageCommand,
     data: any
}
```

</details>

I think we're going to have to coordinate on a standard message structure that will help make messages through the components more othogonal. @nlewis05 and I have been working on getting a more standardized interface for the data editor messages but I feel as if a message standard will bleed into the daffodil side.

I've also been working on a mockup implementation of a standard structure that can be seen here: https://github.com/ctc-oss/daffodil-vscode/blob/data-editor-replace-hexview/src/daffodilDebugger/daffodil.ts
