### ISSUE TITLE
Togglable views between logical view and data view only

### ISSUE THREAD

**Issue by nlewis05** [apache/daffodil-vscode#794]
Either only want the logical view or only the data view in the view port, most of the time you will only need one of these views and data profiling can inform this decision (e.g., does the file only contain printable ASCII?) 

Logical view hide (toggleable view) capability, Mike mentioned that with binary data does not require logical view as it is not byte-oriented data and we can save some screen real estate by hiding logical view.

**Comment by stricklandrbls** [comment]
@nlewis05 @scholarsmate - Going to work this into the PR with #797 

#797 needs to be able to display more bytes per row if only one viewport is displayed and less if both are displayed. I need this functionality to be implemented before I can finish completing #797
