### ISSUE TITLE
Add hover functionality to display the attributes available to specific tags

### ISSUE THREAD

**Issue by nlewis05** [apache/daffodil-vscode#802]
Improving on what's already there and determining when it currently is working and making it more consistent. Currently it's based on the snippet and that would have to be expanded upon.

**Comment by hdalsania** [comment]
@nlewis05  Could you please evaluate this ticket and dispose it appropriately?

**Comment by nlewis05** [comment]
Closed in this PR: https://github.com/apache/daffodil-vscode/pull/874
