### ISSUE TITLE
yarn disallows SVG's in the README

### ISSUE THREAD

**Issue by stevedlawrence** [apache/daffodil-vscode#81]
When running yarn build with yarn version 1.22.15, I get the following error:

> ERROR  SVGs are restricted in README.md; please use other file image formats, such as PNG: https://daffodil.apache.org/assets/themes/apache/img/apache-daffodil-logo.svg

Should we create a png version of the logo on our website that this README can reference?

The README also has links to github workflow badges that are svg. I can't find a way to get png badges instead, but yarn doesn't seem to care about them, so maybe we can ignore them? Alternatively, shields.io (which we use for the Daffodil readme) does seem to have a way to use pngs, although they do not recommend it.

**Comment by Shanedell** [comment]
@stevedlawrence There is already a PNG of the logo out there so that is an easy fix. I have the updates for these latest issues locally I just had one question. Is it okay that I leave the badges for CI? As these SVGs don't cause issues with the build only the logo image did.
