### ISSUE TITLE
Rename vsix convenience binary?

### ISSUE THREAD

**Issue by stevedlawrence** [apache/daffodil-vscode#83]
The .vsix convenience binary created by running yarn buil is currently name `daffodil-debugger-VERSION.vsix`. This doesn't have "apache" in the name, which ASF usually requires. It is also specific to the debugger aspect of this extension, but the extension may very likely grow to include other capabilities (e.g. auto-completion).

Thoughts on renaming the resulting .vsix file to something with apache in the name and more generic like `apache-daffodil-vscode-VERSION.vsix`. This makes it clear that this is specific to vscode, matches the naming of this repository, and matches what the likely source release would look like (e.g. apache-daffodil-vscode-VERSION-src.zip`).

**Comment by tuxji** [comment]
Yes, I agree; +1 from me.

**Comment by jw3** [comment]
> ... apache-daffodil-vscode-VERSION.vsix. This makes it clear that this is specific to vscode, matches the naming of this repository, and matches what the likely source release would look like

:+1:  for the proposed name

Added this to the 1.0.0 milstone
