### ISSUE TITLE
compiled source matches convenience binary where expected

### ISSUE THREAD

**Issue by hdalsania** [apache/daffodil-vscode#840]
- The JAXB generated class files in daffodil-debugger jar are different when I build from source. It's not clear to me what is different
   (javap shows no differences) but this makes reproducible builds difficult to verify and is a bit concerning. I don't know why these
   files would be different. Even if generated from JAXB, I would expect it to be deterministic and create the same .class files. Please look into this for the next major release, reproducible builds are important.

- UUID like element gets randomly generated at each build, which would cause the above behavior. Timestamps are another common culprit. 

Source of this ticket is approval VOTE email from @stevedlawrence for v1.3.1-rc2.

**Comment by michael-hoke** [comment]
There is a timestamp placed in the header of each generated file - will try to remove them and compare outputs between runs.

**Comment by michael-hoke** [comment]
This is a weird one... Adding the `-no-header` flag to xjc seems to resolve this... Waiting on confirmation from Steve to make sure it's not just on my machine. Completely unsure as to why a comment header would result in changes to a .class file, but I don't see any other diffs. I also decompiled two 'differing' class files, and they looked identical to me, so maybe some weird flag in the binary?

Even with all of that, the generated JAXB .java files still differ a little bit between runs. The order of {@link ...} comments are different in a handful of places. The files where this occurs also changes between runs. However, these comment differences do not appear to affect the .class or .jar files.

We should add the -no-header flag on our side, but I will leave this issue open until Steve confirms this is fixed and/or we switch over to scalaxb.

**Comment by michael-hoke** [comment]
Since we won't make the Daffodil 3.6.0 release with the JAXB changes, we may want to include this. If we care about the .vsix file being binary-identical between builds and if this is the only reason it isn't, we can include this change. If we don't care about binary-identical .vsix files, there's no reason to include this change. Once we start using the Daffodil version with the JAXB bindings, any changes made for this will be moved into the Daffodil repository.
