### ISSUE TITLE
Revisit layout of launch wizard

### ISSUE THREAD

**Issue by hdalsania** [apache/daffodil-vscode#846]
The layout of the launch wizard is confusing. You have to scroll past much less relevant stuff to find the "Program" which is the path to the top level schema file - shouldn't be called "program" it should be "Main Schema File", and should be near the top of the dialog.

Source of this ticket is approval VOTE [email](https://lists.apache.org/thread/0gcddqd3mhys5179t8zgkpp51l9oc6nv) from @mbeckerle for v1.3.1-rc1 on 08/29/2023

**Comment by shanedell** [comment]
@mbeckerle Would you have any input on how the layout should be? I assume you will want it to be from most to least important. With that I imagine we want the "program" option and "data" option to be first, I will update the description of these to be better also. But after that what order should things be in going down the page?

**Comment by shanedell** [comment]
@mbeckerle Would you be able to provide some input how the layout that would be best for the launch wizard? Most meaning does it matter where items are other than the schema program and data files should be the first things to show up. Then after that does order matter or not so much?

**Comment by nlewis05** [comment]
#653 may coincide with this layout revision as we might want to add the configuration mentioned
