### ISSUE TITLE
Split the README.md into README.md and DEVELOPMENT.md

### ISSUE THREAD

**Issue by scholarsmate** [apache/daffodil-vscode#853]
`README.md` ought to focus on the end-user (people who are using the extension) and `DEVELOPMENT.md` ought to focus on the developers who are developing the extension.  Developers are getting confused and would like a "single source of truth" for running a proper build.

**Comment by nlewis05** [comment]
https://github.com/ctc-oss/daffodil-vscode/tree/Split-the-README.md-into-README.md-and-DEVELOPMENT.md
