### ISSUE TITLE
Remove HexView

### ISSUE THREAD

**Issue by shanedell** [apache/daffodil-vscode#905]
> Are hexviews still being used? I remember removing the `hexy` capability from the old data editor and don't recall seeing it being used anywhere else throughout the project. Granted I haven't been thoroughly searching.
> _Originally posted by @stricklandrbls in https://github.com/apache/daffodil-vscode/pull/904#discussion_r1409777183_
 
The HexView is out of date and being replaced by omega-edit. This issue is for going through and deleting anything that deals with the hexview as it is no longer used. For something like the button in the menu bar that would open the hexview we may want to have it open the omega-edit editor now instead.

**Comment by lrbarber** [comment]
Is this the HexView that shows the file being parsed - highlighting the current location in the file as the debugger works it's way through the file? If so, please don't remove it until omega-edit can perform this same (or better) functionality.

**Comment by stricklandrbls** [comment]
@shanedell @lrbarber That's the plan but there is currently no such capability within the data editor. I've been working on the #883 PR in order to be able to have a _debugger_ byte indication (among various other categories). 

We intend to start working on being able to communicate between the data editor and debugger.

**Comment by lrbarber** [comment]
The HexView location tracker seems to have stopped working after the latest merges into main

**Comment by stricklandrbls** [comment]
@lrbarber @shanedell @scholarsmate @nlewis05 - After meeting w/ @nlewis05 & @lrbarber  this afternoon, I had a better understanding of the data flow of the dfdl debugging and where the data editor might fit in that.

After some digging, I was able to simply send messages from the dfdl custom debug events and have them be received on the data editor side.

![dfdl-debugger-data-editer-comms](https://github.com/apache/daffodil-vscode/assets/30351915/01bcef88-bb3c-474e-a24e-6289c3547151)

In this screen shot I'm just using the `searchResult` highlight to indicate the `bytePos1b` of the dfdl debugger message.

There will definitely be some data editor / omega editor refactoring to be done but this example shows that communication between the two panels doesn't have to go as low level as defining specific web sockets between them.

**Comment by lrbarber** [comment]
@arosien do you remember if the location information being sent from daffodil to the debugger for the current parsing location include bit offsets, or is it just byte address?
