### ISSUE TITLE
Make daffodilDebugClasspath more extensible

### ISSUE THREAD

**Issue by shanedell** [apache/daffodil-vscode#934]
Something that I noticed with testing changes for #653 is that the `daffodilDebugClasspath` setting can become incredibly long. I think making this setting a JSON object that will that be looped over and join the values together separated by a colon (`:`).

So for example:

#### Snippet 1

```json
{
    ...
   "daffodilDebugClasspath": "${workspaceFolder}/dfdl-mil-std-2045/src/main/resources:${workspaceFolder}/dfdl-mil-std-2045/target/classes:${workspaceFolder}/dfdl-tcpMessage/src/main/resources:${workspaceFolder}/dfdl-tcpMessage/target/classes:${workspaceFolder}/dfdl-pcap/src/main/resources:${workspaceFolder}/dfdl-pcap/target/classes:${workspaceFolder}/dfdl-envelope-payload/src/main/resources:${workspaceFolder}/dfdl-envelope-payload/target/classes:${workspaceFolder}/dfdl-ethernet/src/main/resources:${workspaceFolder}/dfdl-ethernet/target/classes",
    ...
}
```

Could instead be:

#### Snippet 2
```json
{
    ...
    "daffodilDebugClasspath": {
        "dfdl-mil-std-2045": "${workspaceFolder}/dfdl-mil-std-2045/src/main/resources:${workspaceFolder}/dfdl-mil-std-2045/target/classes",
        "dfdl-tcpMessage": "${workspaceFolder}/dfdl-tcpMessage/src/main/resources:${workspaceFolder}/dfdl-tcpMessage/target/classes",
        "dfdl-pcap": "${workspaceFolder}/dfdl-pcap/src/main/resources:${workspaceFolder}/dfdl-pcap/target/classes",
        "dfdl-envelope-payload": "${workspaceFolder}/dfdl-envelope-payload/src/main/resources:${workspaceFolder}/dfdl-envelope-payload/target/classes",
        "dfdl-ethernet": "${workspaceFolder}/dfdl-ethernet/src/main/resources:${workspaceFolder}/dfdl-ethernet/target/classes",
    }
    ...
}
```

Another thing that we could also do is test if the value passed is a directory, if it is the extension won't add the general directory but would instead add `${DIR_PATH}/{src/main/resources,target/classes}`. Then if say its a file like a JAR it just leaves as is and will join in together with the other items. This would than make the above Snippet 2 to be even simpler by only needing this instead:

#### Snippet 3

```json
{
    ...
    "daffodilDebugClasspath": {
        "dfdl-mil-std-2045": "${workspaceFolder}/dfdl-mil-std-2045",
        "dfdl-tcpMessage": "${workspaceFolder}/dfdl-tcpMessage",
        "dfdl-pcap": "${workspaceFolder}/dfdl-pcap",
        "dfdl-envelope-payload": "${workspaceFolder}/dfdl-envelope-payload",
        "dfdl-ethernet": "${workspaceFolder}/dfdl-ethernet",
    }
    ...
}
```

But in the end with exported variable would still contain all paths needed like Snippet 1 manually defines.

What does everyone think about this? 

@mbeckerle @stevedlawrence @scholarsmate @stricklandrbls @NolanMatt @arosien @lrbarber @nlewis05 @hdalsania @rthomas320

**Comment by stevedlawrence** [comment]
I think it's important to be careful about guessing what users want, so I'm not sure I'm a fan of automatically adding `src/main/resources` and `target/classes`, but I don't feel strongly about it. But maybe an alternative would be to have a daffodilDebugClasspath wizard that you can give it project directories, it will search for what it things are resources (e.g. src/main/resource, target/classes, *.jar) and the user can confirm what they want added to the classpath.

Also, another thought on a possible format of daffodilDebugClasspath, what about just an array of strings, e.g.

```json
{
    ...
    "daffodilDebugClasspath": [
        "${workspaceFolder}/dfdl-mil-std-2045/src/main/resources",
        "${workspaceFolder}/dfdl-mil-std-2045/target/classes",
        "${workspaceFolder}/dfdl-tcpMessage/src/main/resources",
        "${workspaceFolder}/dfdl-tcpMessage/target/classes",
        "${workspaceFolder}/dfdl-pcap/src/main/resources",
        "${workspaceFolder}/dfdl-pcap/target/classes",
        "${workspaceFolder}/dfdl-envelope-payload/src/main/resources",
        "${workspaceFolder}/dfdl-envelope-payload/target/classes",
        "${workspaceFolder}/dfdl-ethernet/src/main/resources",
        "${workspaceFolder}/dfdl-ethernet/target/classes"
    ],
    ...
}
```

Also, something to consider is that on Windows the classpath separator is a semicolon instead of colon. Doing it as an array  makes it so you can just join the array with the os specific classpath separator and you don't need something like `str.replace(":", ";")`.

**Comment by shanedell** [comment]
@stevedlawrence That makes sense on auto adding as I don't think its fully necessary. But I like the idea of the daffodilDebugClasspath wizard as a possible feature for the future, maybe separate issue?

I do like your format for daffodilDebugClasspath better than what I suggested as I think it makes look cleaner and would be easier to work with when joining like you mentioned. So, I propose your format is the one the fix for this issue should use and then we make another ticket for a daffodilDebugClasspath Wizard if that something other think would useful.

**Comment by arosien** [comment]
👍 to array of classpath entries

also, there are facilities in vscode to allow hooks to run when supplying variables, and there is a variation where you can run a registered command (with args) to supply the value of a variable, so one could expand the set of jar files or directories like your example.

https://code.visualstudio.com/docs/editor/variables-reference#_input-variables
