### ISSUE TITLE
Update Apache Daffodil VS Code Extension webpage

### ISSUE THREAD

**Issue by nlewis05** [apache/daffodil-vscode#948]
Update https://daffodil.apache.org/vscode/ with a better description of the extension and using correct nomenclature

**Comment by shanedell** [comment]
@nlewis05 What all was envisioned here? Mostly changing `Daffodil VS Code Extension` to be `Apache Daffodil™ Extension for Visual Studio Code` instead?

**Comment by nlewis05** [comment]
> @nlewis05 What all was envisioned here? Mostly changing `Daffodil VS Code Extension` to be `Apache Daffodil™ Extension for Visual Studio Code` instead?

Yes, and updating the description to contain more of the features offered by the extension and what it can be used for
"The Daffodil VS Code Extension is a custom extension developed by Apache for allowing users to debug schemas inside of VS Code. The VS Code Extension also contains a Scala implemation of the Daffodil DAP Debugger that provides the users the ability to debug schemas."

For example, this is what we have on the wiki documentation
"The Apache Daffodil™ Extension for Visual Studio Code is an extension to the Microsoft® Visual Studio Code (VS Code) editor, designed for Data Format Description Language[1](https://github.com/apache/daffodil-vscode/wiki#footnotes) (DFDL) Schema developers. The purpose of the Apache Daffodil™ Extension for Visual Studio Code is to ease the burden on DFDL Schema developers by enabling rapid development of high-quality DFDL Schemas, with syntax highlighting, code completion, data file editing, and debugging of DFDL Schema parsing operations using Apache Daffodil™.
