### ISSUE TITLE
Update variable properties for objects in package.json

### ISSUE THREAD

**Issue by shanedell** [apache/daffodil-vscode#955]
In the `package.json` we create different properties that can be used in the launch.json. However, for our object items we can defined that object properties as well. For example:

```json
"schema": {
  "type": "object",
  "description": "Contains the absolute path to the DFDL schema file, root element name and namespace.",
   "default": {
      "path": "${command:AskForSchemaName}",
      "rootName": null,
      "rootNamespace": null
    }
},
```

should actually be:

```json
"schema": {
  "type": "object",
  "description": "Contains the absolute path to the DFDL schema file, root element name and namespace.",
  "required": ["path"],
  "properties": {
    "path": {
      "type": "string",
      "description": "Absolute path to the DFDL schema file",
      "default": "${command:AskForSchemaName}"
    },
    "rootName": {
      "type": ["string", "null"],
      "description": "Name of the root element",
      "default": null
    },
    "rootNamespace": {
       "type": ["string", "null"],
       "description": "Name of the root element namespace",
       "default": null
     }
   },
   "default": {
      "path": "${command:AskForSchemaName}",
      "rootName": null,
      "rootNamespace": null
    }
},
```

- NOTE: This example is either fixed in or going to be fixed in PR https://github.com/apache/daffodil-vscode/pull/952. This issue will be for fixing all the other items

**Comment by stricklandrbls** [comment]
@shanedell  I would also like to see restricting of enumerated types. For instance, the log levels are strings that can be whatever the user inputs but in the extension a module might only support `info` `debug` or `warn` etc...

This may warrant another ticket though. Thoughts @nlewis05 ?

**Comment by nlewis05** [comment]
Yea I think that may another issue, I'm not sure how that would look within the configuration, or if we already have framework to process that. To specify which specific module within the data editor or debugger, would that require a separate configuration for each module within the package.json? I think that would have to be handled from the module side.

https://github.com/apache/daffodil-vscode/blob/776de38bf75bf01f3748ee0321319e392b3f4a2d/package.json#L504

**Comment by shanedell** [comment]
@stricklandrbls @nlewis05 I am not sure what you mean, with the `enum` it will give the items supported but do you mean making sure nothing other than the options listed items in `enum` are used/entered? If so, that is something that would need to be handled in the TS code as I don't think that is something you can do directly inside of the `package.json`.

**Comment by nlewis05** [comment]
Yes, I believe that is what he is saying, and that was my concern as well that I stated above

**Comment by stricklandrbls** [comment]
@shanedell @nlewis05 would it be possible for there to just be a `<select>` that only holds valid enumerations defined from @nlewis05 's suggested edit?

**Changing:**
https://github.com/apache/daffodil-vscode/blob/776de38bf75bf01f3748ee0321319e392b3f4a2d/src/launchWizard/launchWizard.ts#L713

**To Be:**
```html
<select>
     <option>Debug</option>
     <option>Info</option>
     ...
```

**Comment by shanedell** [comment]
For the launch wizard, yes doing something like you mention either a selection box or a dropdown would be good to have for the both the data editor and daffodil debugger logging level.
