### ISSUE TITLE
Execution not stopping at breakpoints

### ISSUE THREAD

**Issue by lrbarber** [apache/daffodil-vscode#968]
Set a breakpoint on a line that execution stops at while stepping through the parse, but the breakpoint is not hit when I just let it run via Continue(F5)

[google.png](https://github.com/apache/daffodil-vscode/assets/72564532/2607b261-c7cc-4f2e-a51a-628a52cc4e83)
[launch.json](https://github.com/apache/daffodil-vscode/files/14270896/launch.json)

Couldn't attach xsd file without renaming it
[png.dfdl.txt](https://github.com/apache/daffodil-vscode/files/14270937/png.dfdl.txt)

**Comment by lrbarber** [comment]
Looking at the Dapodil history dumped into the terminal window, it seems that the breakpoints are being passed over from VS and accepted/acknowledged by the debugger.

**Comment by rthomas320** [comment]
I ran the debugger with the same schema file png.dfdl.xsd and the same data file google.png in windows 10 and in Rocky 9.  I sent the log for the debugger to DEBUG in both instances.  Below are some screen captures from ByeondCompare.
![image](https://github.com/apache/daffodil-vscode/assets/72815523/83c5ba8a-cfb0-45cb-bb33-28f3dd8cd816)

![image](https://github.com/apache/daffodil-vscode/assets/72815523/63636b98-617e-4c42-97ae-1bf5c5ef1a04)

I am also attached the log files.
[Windows10-daffodil-debugger.log](https://github.com/apache/daffodil-vscode/files/14542612/Windows10-daffodil-debugger.log)
[Rocky9-daffodil-debugger.log](https://github.com/apache/daffodil-vscode/files/14542613/Rocky9-daffodil-debugger.log)

**Comment by arosien** [comment]
> @arosien Are you able to take a look at this?

Sure, will look today. It looks... odd.

**Comment by arosien** [comment]
@lrbarber are you on Windows 9, or is that a different reproduction that @rthomas320 is showing?

For @rthomas320's Windows 9 problem, I suspect that the "is the current schema line in the list of breakpoints" check is failing due to the backslash path convention. The code looks like https://github.com/apache/daffodil-vscode/blob/main/debugger/src/main/scala/org.apache.daffodil.debugger.dap/DAPodil.scala#L754. I don't have a way to run Windows 9, but one could add some logging locally to test these comparisons, or we can try to find a Windows 9 Github action runner.

**Comment by arosien** [comment]
> Rege and I are both on Windows 10.
> 
> Here's the info I see when I set a breakpoint:
> 
> **2024-03-11 16:11:56,608 [io-compute-2] INFO o.a.d.d.d.DAPSession - R> #22 setBreakpoints {"source":{"name":"scpi.dfdl.xsd","path":"c:\Users\larry.barber\Documents\PaxRiver\scpi.dfdl.xsd","sourceReference":0},"lines":[41],"breakpoints":[{"line":41}],"sourceModified":false} 2024-03-11 16:11:56,612 [io-compute-6] INFO o.a.d.d.d.DAPSession - <R #22 setBreakpoints success {"breakpoints":[{"id":0,"verified":true,"line":41,"message":""}]}**
> 
> @arosien You say these slashes are wrong and that could cause the problem?

Not wrong, per se, but the normalization and comparison of the path into URIs may be implemented incorrectly for Windows-style paths. (See previous link to source.) I'll see if I can get a test case failing with the sample paths you've both provided.

**Comment by nlewis05** [comment]
> > Rege and I are both on Windows 10.
> > Here's the info I see when I set a breakpoint:
> > **2024-03-11 16:11:56,608 [io-compute-2] INFO o.a.d.d.d.DAPSession - R> #22 setBreakpoints {"source":{"name":"scpi.dfdl.xsd","path":"c:\Users\larry.barber\Documents\PaxRiver\scpi.dfdl.xsd","sourceReference":0},"lines":[41],"breakpoints":[{"line":41}],"sourceModified":false} 2024-03-11 16:11:56,612 [io-compute-6] INFO o.a.d.d.d.DAPSession - <R #22 setBreakpoints success {"breakpoints":[{"id":0,"verified":true,"line":41,"message":""}]}**
> > @arosien You say these slashes are wrong and that could cause the problem?
> 
> Not wrong, per se, but the normalization and comparison of the path into URIs may be implemented incorrectly for Windows-style paths. (See previous link to source.) I'll see if I can get a test case failing with the sample paths you've both provided.

You have any comments on how this should be implemented?
https://github.com/apache/daffodil-vscode/pull/990#discussion_r1521575132
